name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - staging # Added staging branch for preview deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Vercel Deployment
        run: curl -X POST "${{ secrets.VERCEL_HOOK_URL }}"
